# Generated by Django 4.2.3 on 2023-07-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trip', '0002_destiny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destiny',
            name='photo',
            field=models.ImageField(blank=True, upload_to='destiny_photos'),
        ),
    ]
