# Generated by Django 4.2.3 on 2023-07-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trip', '0003_alter_destiny_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='photo',
            field=models.ImageField(blank=True, upload_to='statement_photos'),
        ),
    ]
