version: '3.9'

services:
  database:
    container_name: database-pg
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data

  api:
    container_name: api
    build: .
    restart: always
    command: >
      sh -c "
        cd /app &&
        poetry run python -m core.manage migrate &&
        poetry run python -m core.manage runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - database
